# IMPORTING LIBRARIES

In [ ]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# LOAD **DATASET**

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/archive (3).zip')
df

,student_id,attendance_pct,homework_pct,midterm_score,study_hours_per_week,pass
0,1,95,92,88,12,1
1,2,88,85,79,10,1
2,3,60,55,58,4,0
3,4,72,70,65,6,1
4,5,40,45,50,3,0
...,...,...,...,...,...,...
95,96,89,92,94,14,1
96,97,79,77,75,8,1
97,98,55,56,58,5,0
98,99,91,90,88,12,1
99,100,52,50,53,4,0

#  CHEAK MISSING VALUES AND DATA PREPROCESSING

In [ ]:
df.isnull().sum()

student_id              0
attendance_pct          0
homework_pct            0
midterm_score           0
study_hours_per_week    0
pass                    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            100 non-null    int64
 1   attendance_pct        100 non-null    int64
 2   homework_pct          100 non-null    int64
 3   midterm_score         100 non-null    int64
 4   study_hours_per_week  100 non-null    int64
 5   pass                  100 non-null    int64
dtypes: int64(6)
memory usage: 4.8 KB

In [ ]:
df.head()

,student_id,attendance_pct,homework_pct,midterm_score,study_hours_per_week,pass
0,1,95,92,88,12,1
1,2,88,85,79,10,1
2,3,60,55,58,4,0
3,4,72,70,65,6,1
4,5,40,45,50,3,0

In [ ]:
df.tail()

,student_id,attendance_pct,homework_pct,midterm_score,study_hours_per_week,pass
95,96,89,92,94,14,1
96,97,79,77,75,8,1
97,98,55,56,58,5,0
98,99,91,90,88,12,1
99,100,52,50,53,4,0

In [ ]:
df.dtypes

student_id              int64
attendance_pct          int64
homework_pct            int64
midterm_score           int64
study_hours_per_week    int64
pass                    int64
dtype: object

In [ ]:
x=df.iloc[:,:-1]
x

,student_id,attendance_pct,homework_pct,midterm_score,study_hours_per_week
0,1,95,92,88,12
1,2,88,85,79,10
2,3,60,55,58,4
3,4,72,70,65,6
4,5,40,45,50,3
...,...,...,...,...,...
95,96,89,92,94,14
96,97,79,77,75,8
97,98,55,56,58,5
98,99,91,90,88,12
99,100,52,50,53,4

In [ ]:
y=df.iloc[:,-1]
y

0     1
1     1
2     0
3     1
4     0
     ..
95    1
96    1
97    0
98    1
99    0
Name: pass, Length: 100, dtype: int64

###              SCALING

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

array([[0.        , 1.        , 0.93442623, 0.83636364, 0.76923077],
       [0.01010101, 0.89230769, 0.81967213, 0.67272727, 0.61538462],
       [0.02020202, 0.46153846, 0.32786885, 0.29090909, 0.15384615],
       [0.03030303, 0.64615385, 0.57377049, 0.41818182, 0.30769231],
       [0.04040404, 0.15384615, 0.16393443, 0.14545455, 0.07692308],
       [0.05050505, 0.84615385, 0.90163934, 0.89090909, 0.92307692],
       [0.06060606, 0.73846154, 0.73770492, 0.58181818, 0.46153846],
       [0.07070707, 0.38461538, 0.40983607, 0.36363636, 0.23076923],
       [0.08080808, 0.92307692, 0.86885246, 0.76363636, 0.69230769],
       [0.09090909, 0.58461538, 0.49180328, 0.32727273, 0.30769231],
       [0.1010101 , 0.        , 0.        , 0.        , 0.        ],
       [0.11111111, 0.8       , 0.70491803, 0.61818182, 0.53846154],
       [0.12121212, 0.67692308, 0.57377049, 0.47272727, 0.38461538],
       [0.13131313, 0.30769231, 0.21311475, 0.23636364, 0.15384615],
       [0.14141414, 0.95384615, 0.98360656, 0.92727273, 1.        ],
       [0.15151515, 0.53846154, 0.40983607, 0.30909091, 0.23076923],
       [0.16161616, 0.76923077, 0.81967213, 0.72727273, 0.61538462],
       [0.17171717, 0.23076923, 0.24590164, 0.18181818, 0.07692308],
       [0.18181818, 0.89230769, 0.90163934, 0.8       , 0.76923077],
       [0.19191919, 0.61538462, 0.54098361, 0.43636364, 0.38461538],
       [0.2020202 , 0.43076923, 0.32786885, 0.27272727, 0.15384615],
       [0.21212121, 0.81538462, 0.73770492, 0.65454545, 0.53846154],
       [0.22222222, 0.07692308, 0.08196721, 0.10909091, 0.        ],
       [0.23232323, 0.70769231, 0.60655738, 0.50909091, 0.46153846],
       [0.24242424, 0.92307692, 0.86885246, 0.78181818, 0.69230769],
       [0.25252525, 0.49230769, 0.40983607, 0.29090909, 0.23076923],
       [0.26262626, 0.27692308, 0.16393443, 0.14545455, 0.07692308],
       [0.27272727, 0.86153846, 0.80327869, 0.69090909, 0.61538462],
       [0.28282828, 0.56923077, 0.49180328, 0.38181818, 0.30769231],
       [0.29292929, 0.33846154, 0.24590164, 0.21818182, 0.15384615],
       [0.3030303 , 0.93846154, 0.8852459 , 0.81818182, 0.76923077],
       [0.31313131, 0.83076923, 0.7704918 , 0.67272727, 0.53846154],
       [0.32323232, 0.44615385, 0.36065574, 0.25454545, 0.15384615],
       [0.33333333, 0.66153846, 0.59016393, 0.49090909, 0.38461538],
       [0.34343434, 0.18461538, 0.14754098, 0.12727273, 0.07692308],
       [0.35353535, 0.87692308, 0.90163934, 0.90909091, 0.92307692],
       [0.36363636, 0.75384615, 0.70491803, 0.6       , 0.46153846],
       [0.37373737, 0.4       , 0.37704918, 0.32727273, 0.23076923],
       [0.38383838, 0.90769231, 0.85245902, 0.74545455, 0.69230769],
       [0.39393939, 0.6       , 0.50819672, 0.4       , 0.30769231],
       [0.4040404 , 0.04615385, 0.04918033, 0.05454545, 0.        ],
       [0.41414141, 0.78461538, 0.72131148, 0.63636364, 0.53846154],
       [0.42424242, 0.69230769, 0.60655738, 0.50909091, 0.38461538],
       [0.43434343, 0.32307692, 0.2295082 , 0.2       , 0.15384615],
       [0.44444444, 0.96923077, 0.96721311, 0.96363636, 1.        ],
       [0.45454545, 0.52307692, 0.42622951, 0.32727273, 0.23076923],
       [0.46464646, 0.8       , 0.83606557, 0.76363636, 0.61538462],
       [0.47474747, 0.24615385, 0.27868852, 0.21818182, 0.07692308],
       [0.48484848, 0.87692308, 0.8852459 , 0.78181818, 0.76923077],
       [0.49494949, 0.63076923, 0.55737705, 0.45454545, 0.38461538],
       [0.50505051, 0.41538462, 0.3442623 , 0.29090909, 0.15384615],
       [0.51515152, 0.83076923, 0.75409836, 0.67272727, 0.53846154],
       [0.52525253, 0.09230769, 0.09836066, 0.09090909, 0.        ],
       [0.53535354, 0.72307692, 0.62295082, 0.52727273, 0.46153846],
       [0.54545455, 0.90769231, 0.86885246, 0.8       , 0.69230769],
       [0.55555556, 0.50769231, 0.44262295, 0.30909091, 0.23076923],
       [0.56565657, 0.29230769, 0.18032787, 0.16363636, 0.07692308],
       [0.57575758, 0.84615385, 0.78688525, 0.70909091, 0.61538462],
       [0.58585859, 0.58461538, 0.50819672, 0.4       , 0.30769231],
       [0.5959596 , 0.35384615, 0.26229508, 0.23636364, 0.15384615],
       [0.60606061, 0.95384615, 0.91803279, 0.85454545, 0.84615385],
       [0.61616162, 0.86153846, 0.80327869, 0.72727273, 0.61538462],
       [0.62626263, 0.47692308, 0.39344262, 0.27272727, 0.15384615],
       [0.63636364, 0.67692308, 0.60655738, 0.49090909, 0.38461538],
       [0.64646465, 0.2       , 0.16393443, 0.14545455, 0.07692308],
       [0.65656566, 0.89230769, 0.91803279, 0.92727273, 0.92307692],
       [0.66666667, 0.76923077, 0.72131148, 0.61818182, 0.46153846],
       [0.67676768, 0.36923077, 0.36065574, 0.30909091, 0.23076923],
       [0.68686869, 0.93846154, 0.8852459 , 0.78181818, 0.69230769],
       [0.6969697 , 0.61538462, 0.52459016, 0.41818182, 0.30769231],
       [0.70707071, 0.06153846, 0.06557377, 0.03636364, 0.        ],
       [0.71717172, 0.81538462, 0.73770492, 0.65454545, 0.53846154],
       [0.72727273, 0.70769231, 0.63934426, 0.54545455, 0.46153846],
       [0.73737374, 0.30769231, 0.19672131, 0.18181818, 0.15384615],
       [0.74747475, 0.98461538, 1.        , 1.        , 1.        ],
       [0.75757576, 0.55384615, 0.45901639, 0.34545455, 0.23076923],
       [0.76767677, 0.78461538, 0.85245902, 0.78181818, 0.61538462],
       [0.77777778, 0.26153846, 0.29508197, 0.23636364, 0.07692308],
       [0.78787879, 0.89230769, 0.90163934, 0.81818182, 0.76923077],
       [0.7979798 , 0.64615385, 0.57377049, 0.47272727, 0.38461538],
       [0.80808081, 0.4       , 0.31147541, 0.25454545, 0.15384615],
       [0.81818182, 0.84615385, 0.7704918 , 0.69090909, 0.53846154],
       [0.82828283, 0.12307692, 0.1147541 , 0.07272727, 0.        ],
       [0.83838384, 0.73846154, 0.6557377 , 0.56363636, 0.46153846],
       [0.84848485, 0.92307692, 0.8852459 , 0.83636364, 0.69230769],
       [0.85858586, 0.47692308, 0.40983607, 0.29090909, 0.23076923],
       [0.86868687, 0.27692308, 0.14754098, 0.12727273, 0.07692308],
       [0.87878788, 0.87692308, 0.81967213, 0.74545455, 0.61538462],
       [0.88888889, 0.6       , 0.52459016, 0.41818182, 0.30769231],
       [0.8989899 , 0.36923077, 0.27868852, 0.23636364, 0.15384615],
       [0.90909091, 0.96923077, 0.93442623, 0.87272727, 0.84615385],
       [0.91919192, 0.83076923, 0.78688525, 0.70909091, 0.61538462],
       [0.92929293, 0.46153846, 0.37704918, 0.25454545, 0.15384615],
       [0.93939394, 0.69230769, 0.62295082, 0.50909091, 0.38461538],
       [0.94949495, 0.16923077, 0.13114754, 0.10909091, 0.07692308],
       [0.95959596, 0.90769231, 0.93442623, 0.94545455, 0.92307692],
       [0.96969697, 0.75384615, 0.68852459, 0.6       , 0.46153846],
       [0.97979798, 0.38461538, 0.3442623 , 0.29090909, 0.23076923],
       [0.98989899, 0.93846154, 0.90163934, 0.83636364, 0.76923077],
       [1.        , 0.33846154, 0.24590164, 0.2       , 0.15384615]])

# SPLIT

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.3,random_state=0)

In [ ]:
x_train.shape

(70, 5)

In [ ]:
x_test.shape

(30, 5)

# MODELING

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [ ]:
confusion_matrix(y_pred,y_test)

array([[14,  0],
       [ 1, 15]])

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.94      0.97        16

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

In [ ]:
knn=KNeighborsClassifier(n_neighbors=5)
svm=SVC()
dt=DecisionTreeClassifier(criterion='entropy')
rf=RandomForestClassifier()

In [ ]:
models=(knn,svm,dt,rf)
for model in models:
  print(model)
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  print(accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test,y_pred))
  print(classification_report(y_test,y_pred))

KNeighborsClassifier()
0.9666666666666667
[[14  1]
 [ 0 15]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

SVC()
0.9666666666666667
[[14  1]
 [ 0 15]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

DecisionTreeClassifier(criterion='entropy')
1.0
[[15  0]
 [ 0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

RandomForestClassifier()
1.0
[[15  0]
 [ 0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

#         BEST MODEL
model:RandomForest                                                          
accuray:100%